language: C++
os:
  - linux

before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade cmake
  - openssl aes-256-cbc -K $encrypted_41727c432bd7_key -iv $encrypted_41727c432bd7_iv -in docs/deploy_key.enc -out docs/deploy_key -d
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5

env:
  global:
  - ENCRYPTION_LABEL: "41727c432bd7"
  - COMMIT_AUTHOR_EMAIL: "travis-ci@lusito.info"

script:
  - cmake -G"Unix Makefiles"
  - make
  - ./tests
  - cd docs
  - ./deploy.sh
